services: # Lightweight busybox httpd
  frontend:
    build: Frontend
    ports:
      - 12380:80
    volumes:
      - ./Frontend:/var/www:ro
    environment:
      - NGINX_HOST=frontend
      - NGINX_PORT=80
      - NGINX_CORS_ALLOWED=backend
  backend: # Swagger based
    build: Backend/swagger_codegen
#    ports: 
#    - 8080:8080
    volumes:
      - ./Backend/swagger_codegen:/usr/src/app # Development only
    depends_on:
      - mongodb
    command: python -m swagger_server
    environment:
      MONGODB_URL: mongodb
  mongodb: # MondoDB
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#    - 27017:27017

    volumes:
    - ./Database/database:/data
  mongo-express:
    image: mongo-express
    restart: always
#    ports:
#      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
#  mongo-populate: # MondoDB populator (for testing purposes only)
#    build: Database/populate
#    depends_on:
#      - "mongodb"
#    environment:
#      MONGODB_URL: mongodb://root:example@mongodb:27017/
